-- LAJE-112 — constraints CHECK do schema public.

ALTER TABLE public.championship_award_draw_results ADD CONSTRAINT championship_award_draw_results_winner_shape_check CHECK (award_type = 'TOP_SCORER'::championship_award_type AND winner_player_id IS NOT NULL AND winner_team_id IS NULL OR award_type = 'BEST_GOALKEEPER'::championship_award_type AND winner_player_id IS NULL AND winner_team_id IS NOT NULL);
ALTER TABLE public.championship_award_players ADD CONSTRAINT championship_award_players_name_not_blank CHECK (length(TRIM(BOTH FROM name)) > 0);
ALTER TABLE public.championship_bracket_competitions ADD CONSTRAINT championship_bracket_competitions_groups_count_positive CHECK (groups_count > 0);
ALTER TABLE public.championship_bracket_competitions ADD CONSTRAINT championship_bracket_competitions_knockout_pairing_mode_check CHECK (knockout_pairing_mode = ANY (ARRAY['LINEAR'::text, 'RANKING_ALTERNATING'::text, 'CLASSIC_SEEDED'::text]));
ALTER TABLE public.championship_bracket_competitions ADD CONSTRAINT championship_bracket_competitions_qualifiers_positive CHECK (qualifiers_per_group > 0);
ALTER TABLE public.championship_bracket_court_sports ADD CONSTRAINT championship_bracket_court_sports_sequence_mode_preferences_che CHECK (sequence_mode = 'FLEXIBLE'::bracket_court_sequence_mode OR (sequence_mode = ANY (ARRAY['GROUP_NAIPE'::bracket_court_sequence_mode, 'ALTERNATE_NAIPE'::bracket_court_sequence_mode])) AND preferred_naipe IS NOT NULL AND preferred_division IS NULL OR sequence_mode = 'GROUP_DIVISION'::bracket_court_sequence_mode AND preferred_division IS NOT NULL AND preferred_naipe IS NULL);
ALTER TABLE public.championship_bracket_day_breaks ADD CONSTRAINT championship_bracket_day_breaks_check CHECK (break_end_time > break_start_time);
ALTER TABLE public.championship_bracket_days ADD CONSTRAINT championship_bracket_days_break_window_valid CHECK (break_start_time IS NULL AND break_end_time IS NULL OR break_start_time IS NOT NULL AND break_end_time IS NOT NULL AND break_end_time > break_start_time AND break_start_time >= start_time AND break_end_time <= end_time);
ALTER TABLE public.championship_bracket_days ADD CONSTRAINT championship_bracket_days_time_order CHECK (end_time > start_time);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_duration_check CHECK (duration_minutes > 0);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_end_date_check CHECK ((end_at AT TIME ZONE 'America/Sao_Paulo'::text)::date = scheduled_date);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_interval_check CHECK (end_at > start_at);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_queue_check CHECK (queue_position > 0);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_round_check CHECK (round_number > 0);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_scheduled_slot_check CHECK (scheduled_slot > 0);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_slot_check CHECK (slot_number > 0);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_start_date_check CHECK ((start_at AT TIME ZONE 'America/Sao_Paulo'::text)::date = scheduled_date);
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT chk_group_stage_requires_match_id CHECK (phase <> 'GROUP_STAGE'::bracket_phase OR match_id IS NOT NULL);
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_attempt_one_centimeters_c CHECK (attempt_one_centimeters IS NULL OR attempt_one_centimeters >= 0);
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_attempt_three_centimeters CHECK (attempt_three_centimeters IS NULL OR attempt_three_centimeters >= 0);
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_attempt_two_centimeters_c CHECK (attempt_two_centimeters IS NULL OR attempt_two_centimeters >= 0);
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_final_position_check CHECK (final_position IS NULL OR final_position >= 1);
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_lane_number_check CHECK (lane_number IS NULL OR lane_number > 0);
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_recording_mode_check CHECK (recording_mode = ANY (ARRAY['ATHLETE_METRIC'::text, 'TEAM_PLACEMENT'::text]));
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_result_mark_centimeters_c CHECK (result_mark_centimeters IS NULL OR result_mark_centimeters >= 0);
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_result_time_milliseconds_ CHECK (result_time_milliseconds IS NULL OR result_time_milliseconds >= 0);
ALTER TABLE public.championship_interlaje_individual_tie_break_resolutions ADD CONSTRAINT championship_interlaje_individual_tie_break_decision_kind_check CHECK (decision_kind = ANY (ARRAY['SWIM_OFF'::text, 'REPEAT_MARK'::text, 'CAMERA'::text]));
ALTER TABLE public.championship_interlaje_individual_tie_break_resolutions ADD CONSTRAINT championship_interlaje_individual_tie_break_justification_check CHECK (length(TRIM(BOTH FROM justification)) > 0);
ALTER TABLE public.championship_interlaje_ranking_audits ADD CONSTRAINT championship_interlaje_ranking_audits_action_check CHECK (action = ANY (ARRAY['UNCHANGED'::text, 'REGENERATED'::text, 'BLOCKED_STARTED_KNOCKOUT'::text, 'PENDING_TIE_BREAK'::text]));
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_break_resolution_decision_kind_check CHECK (decision_kind = ANY (ARRAY['DRAW'::text, 'ARBITRATION'::text, 'CAMERA'::text, 'SWIM_OFF'::text, 'REPEAT_MARK'::text]));
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_break_resolution_justification_check CHECK (length(TRIM(BOTH FROM justification)) > 0);
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_break_resolutions_draw_order_check CHECK (draw_order > 0);
ALTER TABLE public.championship_knockout_result_corrections ADD CONSTRAINT championship_knockout_result_corrections_walkover_mode_check CHECK (walkover_mode = ANY (ARRAY['HOME_LOST'::text, 'AWAY_LOST'::text]));
ALTER TABLE public.championship_opening_ceremony_bonus_settings ADD CONSTRAINT championship_opening_ceremony_bonus_settings_points_check CHECK (points > 0);
ALTER TABLE public.championship_opening_ceremony_bonus_settings ADD CONSTRAINT championship_opening_ceremony_bonus_settings_season_year_check CHECK (season_year >= 2024);
ALTER TABLE public.championship_overall_competition_placements ADD CONSTRAINT championship_overall_competition_placement_final_position_check CHECK (final_position >= 1 AND final_position <= 20);
ALTER TABLE public.championship_overall_competition_placements ADD CONSTRAINT championship_overall_competition_placements_source_check CHECK (source = ANY (ARRAY['MANUAL'::text, 'AUTO_KNOCKOUT'::text]));
ALTER TABLE public.championship_overall_position_point_settings ADD CONSTRAINT championship_overall_position_point_settin_final_position_check CHECK (final_position >= 1 AND final_position <= 20);
ALTER TABLE public.championship_overall_position_point_settings ADD CONSTRAINT championship_overall_position_point_settings_points_check CHECK (points >= 0);
ALTER TABLE public.championship_overall_position_point_settings ADD CONSTRAINT championship_overall_position_point_settings_season_year_check CHECK (season_year >= 2024);
ALTER TABLE public.championship_overall_score_adjustments ADD CONSTRAINT championship_overall_score_adjustments_adjustment_type_check CHECK (adjustment_type = 'OPENING_CEREMONY'::text);
ALTER TABLE public.championship_overall_score_adjustments ADD CONSTRAINT championship_overall_score_adjustments_justification_check CHECK (char_length(TRIM(BOTH FROM justification)) > 0);
ALTER TABLE public.championship_overall_score_adjustments ADD CONSTRAINT championship_overall_score_adjustments_points_check CHECK (adjustment_type <> 'OPENING_CEREMONY'::text OR points > 0::numeric AND points = trunc(points));
ALTER TABLE public.championship_overall_tie_break_resolution_teams ADD CONSTRAINT championship_overall_tie_break_resolution_team_draw_order_check CHECK (draw_order > 0);
ALTER TABLE public.championship_season_division_movements ADD CONSTRAINT championship_season_division_movements_ranking_position_check CHECK (ranking_position > 0);
ALTER TABLE public.championship_season_division_movements ADD CONSTRAINT championship_season_division_movements_season_year_check CHECK (season_year >= 2024);
ALTER TABLE public.championship_season_settings ADD CONSTRAINT championship_season_settings_access_promotion_count_check CHECK (access_promotion_count IS NULL OR access_promotion_count >= 0);
ALTER TABLE public.championship_season_settings ADD CONSTRAINT championship_season_settings_principal_relegation_count_check CHECK (principal_relegation_count IS NULL OR principal_relegation_count >= 0);
ALTER TABLE public.championship_season_settings ADD CONSTRAINT championship_season_settings_principal_slots_count_check CHECK (principal_slots_count IS NULL OR principal_slots_count > 0);
ALTER TABLE public.championship_season_settings ADD CONSTRAINT championship_season_settings_season_year_check CHECK (season_year >= 2024);
ALTER TABLE public.championship_season_settings ADD CONSTRAINT championship_season_settings_yellow_card_reset_phase_check CHECK (yellow_card_reset_phase = ANY (ARRAY['NONE'::text, 'QUARTERFINAL'::text, 'SEMIFINAL'::text]));
ALTER TABLE public.championship_sports ADD CONSTRAINT championship_sports_default_match_duration_positive CHECK (default_match_duration_minutes > 0);
ALTER TABLE public.championship_sports ADD CONSTRAINT championship_sports_walkover_winner_points_positive CHECK (walkover_winner_points IS NULL OR walkover_winner_points > 0);
ALTER TABLE public.championship_sports ADD CONSTRAINT championship_sports_walkover_winner_set_count_positive CHECK (walkover_winner_set_count > 0);
ALTER TABLE public.championship_walkover_penalty_counts ADD CONSTRAINT championship_walkover_penalty_counts_season_year_check CHECK (season_year >= 2024);
ALTER TABLE public.championship_walkover_penalty_counts ADD CONSTRAINT championship_walkover_penalty_counts_walkover_count_check CHECK (walkover_count > 0);
ALTER TABLE public.championship_walkover_penalty_settings ADD CONSTRAINT championship_walkover_penalty_settings_points_check CHECK (points > 0);
ALTER TABLE public.championship_walkover_penalty_settings ADD CONSTRAINT championship_walkover_penalty_settings_season_year_check CHECK (season_year >= 2024);
ALTER TABLE public.league_events ADD CONSTRAINT league_events_laje_event_must_be_laje_organizer_check CHECK (event_type <> 'LAJE_EVENT'::league_event_type OR organizer_type = 'LAJE'::league_event_organizer_type);
ALTER TABLE public.league_events ADD CONSTRAINT league_events_organizer_consistency_check CHECK (organizer_type = 'LAJE'::league_event_organizer_type AND organizer_team_id IS NULL OR organizer_type = 'ATHLETIC'::league_event_organizer_type AND organizer_team_id IS NOT NULL);
ALTER TABLE public.match_award_goal_scorers ADD CONSTRAINT match_award_goal_scorers_goal_order_positive CHECK (goal_order > 0);
ALTER TABLE public.match_blue_card_players ADD CONSTRAINT match_blue_card_players_card_order_check CHECK (card_order > 0);
ALTER TABLE public.match_red_card_players ADD CONSTRAINT match_red_card_players_card_order_check CHECK (card_order > 0);
ALTER TABLE public.match_sets ADD CONSTRAINT match_sets_away_points_non_negative CHECK (away_points >= 0);
ALTER TABLE public.match_sets ADD CONSTRAINT match_sets_home_points_non_negative CHECK (home_points >= 0);
ALTER TABLE public.match_sets ADD CONSTRAINT match_sets_set_number_positive CHECK (set_number > 0);
ALTER TABLE public.match_yellow_card_players ADD CONSTRAINT match_yellow_card_players_card_order_check CHECK (card_order > 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_away_penalty_score_non_negative CHECK (away_penalty_score IS NULL OR away_penalty_score >= 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_away_red_cards_non_negative CHECK (away_red_cards >= 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_away_yellow_cards_non_negative CHECK (away_yellow_cards >= 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_current_set_away_score_non_negative CHECK (current_set_away_score IS NULL OR current_set_away_score >= 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_current_set_home_score_non_negative CHECK (current_set_home_score IS NULL OR current_set_home_score >= 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_global_queue_order_check CHECK (global_queue_order IS NULL OR global_queue_order > 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_home_penalty_score_non_negative CHECK (home_penalty_score IS NULL OR home_penalty_score >= 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_home_red_cards_non_negative CHECK (home_red_cards >= 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_home_yellow_cards_non_negative CHECK (home_yellow_cards >= 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_manual_representation_mode_check CHECK (manual_representation_mode = ANY (ARRAY['AUTO'::text, 'CO'::text]));
ALTER TABLE public.matches ADD CONSTRAINT matches_manual_schedule_override_reason_check CHECK (is_manual_schedule_override = false AND manual_schedule_override_reason IS NULL AND manual_schedule_override_notes IS NULL OR is_manual_schedule_override = true AND (manual_schedule_override_reason = ANY (ARRAY['WEATHER'::text, 'COURT_UNAVAILABLE'::text, 'OPERATIONAL_DELAY'::text, 'SAFETY'::text, 'OTHER'::text])));
ALTER TABLE public.matches ADD CONSTRAINT matches_pending_manual_relocation_check CHECK (is_pending_manual_relocation = false AND pending_manual_relocation_reason IS NULL AND pending_manual_relocation_notes IS NULL AND pending_manual_relocation_previous_schedule IS NULL AND pending_manual_relocation_previous_label IS NULL AND pending_manual_relocation_created_by IS NULL AND pending_manual_relocation_at IS NULL OR is_pending_manual_relocation = true AND (pending_manual_relocation_reason = ANY (ARRAY['WEATHER'::text, 'COURT_UNAVAILABLE'::text, 'OPERATIONAL_DELAY'::text, 'SAFETY'::text, 'OTHER'::text])) AND pending_manual_relocation_previous_schedule IS NOT NULL AND pending_manual_relocation_previous_label IS NOT NULL AND pending_manual_relocation_created_by IS NOT NULL AND pending_manual_relocation_at IS NOT NULL);
ALTER TABLE public.matches ADD CONSTRAINT matches_queue_position_positive CHECK (queue_position IS NULL OR queue_position > 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_scheduled_slot_check CHECK (scheduled_slot IS NULL OR scheduled_slot > 0);
ALTER TABLE public.matches ADD CONSTRAINT matches_walkover_consistency_check CHECK (is_walkover = false AND is_double_walkover = false AND walkover_loser_team_id IS NULL OR is_walkover = true AND is_double_walkover = false AND walkover_loser_team_id IS NOT NULL AND (walkover_loser_team_id = home_team_id OR walkover_loser_team_id = away_team_id) OR is_walkover = true AND is_double_walkover = true AND walkover_loser_team_id IS NULL);
ALTER TABLE public.public_link_item_filters ADD CONSTRAINT public_link_item_filters_season_year_check CHECK (season_year >= 2000 AND season_year <= 9999);
ALTER TABLE public.public_link_items ADD CONSTRAINT public_link_items_display_name_not_blank CHECK (length(TRIM(BOTH FROM display_name)) > 0);
ALTER TABLE public.public_link_items ADD CONSTRAINT public_link_items_url_not_blank CHECK (length(TRIM(BOTH FROM url)) > 0);
ALTER TABLE public.public_link_sections ADD CONSTRAINT public_link_sections_name_not_blank CHECK (length(TRIM(BOTH FROM name)) > 0);
ALTER TABLE public.public_page_access_settings ADD CONSTRAINT public_page_access_settings_announcement_type_check CHECK (announcement_type = ANY (ARRAY['IMPROVEMENT'::text, 'NOTICE'::text, 'PROBLEM'::text]));
ALTER TABLE public.public_page_access_settings ADD CONSTRAINT public_page_access_settings_single_row_check CHECK (id = 1);
ALTER TABLE public.sports ADD CONSTRAINT sports_default_match_duration_positive CHECK (default_match_duration_minutes > 0);
ALTER TABLE public.standings ADD CONSTRAINT standings_red_cards_non_negative CHECK (red_cards >= 0);
ALTER TABLE public.standings ADD CONSTRAINT standings_yellow_cards_non_negative CHECK (yellow_cards >= 0);
