-- LAJE-112 — foreign keys internas ao schema public.
-- As 15 FKs para auth.users foram intencionalmente omitidas e estão documentadas para LAJE-85.

ALTER TABLE public.admin_profile_permissions ADD CONSTRAINT admin_profile_permissions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES admin_profiles(id) ON DELETE CASCADE;
ALTER TABLE public.admin_user_profiles ADD CONSTRAINT admin_user_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES admin_profiles(id) ON DELETE RESTRICT;
ALTER TABLE public.championship_award_draw_results ADD CONSTRAINT championship_award_draw_results_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_award_draw_results ADD CONSTRAINT championship_award_draw_results_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id);
ALTER TABLE public.championship_award_draw_results ADD CONSTRAINT championship_award_draw_results_winner_player_id_fkey FOREIGN KEY (winner_player_id) REFERENCES championship_award_players(id) ON DELETE CASCADE;
ALTER TABLE public.championship_award_draw_results ADD CONSTRAINT championship_award_draw_results_winner_team_id_fkey FOREIGN KEY (winner_team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_award_players ADD CONSTRAINT championship_award_players_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_award_players ADD CONSTRAINT championship_award_players_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE RESTRICT;
ALTER TABLE public.championship_award_players ADD CONSTRAINT championship_award_players_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE RESTRICT;
ALTER TABLE public.championship_bracket_competitions ADD CONSTRAINT championship_bracket_competitions_bracket_edition_id_fkey FOREIGN KEY (bracket_edition_id) REFERENCES championship_bracket_editions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_competitions ADD CONSTRAINT championship_bracket_competitions_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_court_sports ADD CONSTRAINT championship_bracket_court_sports_bracket_court_id_fkey FOREIGN KEY (bracket_court_id) REFERENCES championship_bracket_courts(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_court_sports ADD CONSTRAINT championship_bracket_court_sports_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_courts ADD CONSTRAINT championship_bracket_courts_bracket_location_id_fkey FOREIGN KEY (bracket_location_id) REFERENCES championship_bracket_locations(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_courts ADD CONSTRAINT championship_bracket_courts_preferred_sport_id_fkey FOREIGN KEY (preferred_sport_id) REFERENCES sports(id) ON DELETE SET NULL;
ALTER TABLE public.championship_bracket_day_breaks ADD CONSTRAINT championship_bracket_day_breaks_bracket_court_id_fkey FOREIGN KEY (bracket_court_id) REFERENCES championship_bracket_courts(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_day_breaks ADD CONSTRAINT championship_bracket_day_breaks_bracket_day_id_fkey FOREIGN KEY (bracket_day_id) REFERENCES championship_bracket_days(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_days ADD CONSTRAINT championship_bracket_days_bracket_edition_id_fkey FOREIGN KEY (bracket_edition_id) REFERENCES championship_bracket_editions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_editions ADD CONSTRAINT championship_bracket_editions_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_group_teams ADD CONSTRAINT championship_bracket_group_teams_group_id_fkey FOREIGN KEY (group_id) REFERENCES championship_bracket_groups(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_group_teams ADD CONSTRAINT championship_bracket_group_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_groups ADD CONSTRAINT championship_bracket_groups_competition_id_fkey FOREIGN KEY (competition_id) REFERENCES championship_bracket_competitions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_knockout_court_priorities ADD CONSTRAINT championship_bracket_knockout_court_pri_bracket_edition_id_fkey FOREIGN KEY (bracket_edition_id) REFERENCES championship_bracket_editions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_knockout_court_priorities ADD CONSTRAINT championship_bracket_knockout_court_priorities_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_competition_fkey FOREIGN KEY (competition_id) REFERENCES championship_bracket_competitions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_court_fkey FOREIGN KEY (bracket_court_id) REFERENCES championship_bracket_courts(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_day_fkey FOREIGN KEY (bracket_day_id) REFERENCES championship_bracket_days(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_edition_fkey FOREIGN KEY (bracket_edition_id) REFERENCES championship_bracket_editions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_location_sport_priorities ADD CONSTRAINT championship_bracket_location_sport_pri_bracket_edition_id_fkey FOREIGN KEY (bracket_edition_id) REFERENCES championship_bracket_editions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_location_sport_priorities ADD CONSTRAINT championship_bracket_location_sport_priorities_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_location_template_court_sports ADD CONSTRAINT championship_bracket_location_t_location_template_court_id_fkey FOREIGN KEY (location_template_court_id) REFERENCES championship_bracket_location_template_courts(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_location_template_court_sports ADD CONSTRAINT championship_bracket_location_template_court_spor_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_location_template_courts ADD CONSTRAINT championship_bracket_location_templat_location_template_id_fkey FOREIGN KEY (location_template_id) REFERENCES championship_bracket_location_templates(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_locations ADD CONSTRAINT championship_bracket_locations_bracket_day_id_fkey FOREIGN KEY (bracket_day_id) REFERENCES championship_bracket_days(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_bracket_edition_id_fkey FOREIGN KEY (bracket_edition_id) REFERENCES championship_bracket_editions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_competition_id_fkey FOREIGN KEY (competition_id) REFERENCES championship_bracket_competitions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_group_id_fkey FOREIGN KEY (group_id) REFERENCES championship_bracket_groups(id) ON DELETE SET NULL;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE SET NULL;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_next_bracket_match_id_fkey FOREIGN KEY (next_bracket_match_id) REFERENCES championship_bracket_matches(id) ON DELETE SET NULL;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_source_away_bracket_match_id_fkey FOREIGN KEY (source_away_bracket_match_id) REFERENCES championship_bracket_matches(id) ON DELETE SET NULL;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_source_home_bracket_match_id_fkey FOREIGN KEY (source_home_bracket_match_id) REFERENCES championship_bracket_matches(id) ON DELETE SET NULL;
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_winner_team_id_fkey FOREIGN KEY (winner_team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.championship_bracket_team_modalities ADD CONSTRAINT championship_bracket_team_modalities_bracket_edition_id_fkey FOREIGN KEY (bracket_edition_id) REFERENCES championship_bracket_editions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_team_modalities ADD CONSTRAINT championship_bracket_team_modalities_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_team_modalities ADD CONSTRAINT championship_bracket_team_modalities_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_team_registrations ADD CONSTRAINT championship_bracket_team_registrations_bracket_edition_id_fkey FOREIGN KEY (bracket_edition_id) REFERENCES championship_bracket_editions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_team_registrations ADD CONSTRAINT championship_bracket_team_registrations_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_tie_break_resolution_teams ADD CONSTRAINT championship_bracket_tie_break_resolution_te_resolution_id_fkey FOREIGN KEY (resolution_id) REFERENCES championship_bracket_tie_break_resolutions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_tie_break_resolution_teams ADD CONSTRAINT championship_bracket_tie_break_resolution_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_tie_break_resolutions ADD CONSTRAINT championship_bracket_tie_break_resoluti_bracket_edition_id_fkey FOREIGN KEY (bracket_edition_id) REFERENCES championship_bracket_editions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_tie_break_resolutions ADD CONSTRAINT championship_bracket_tie_break_resolutions_competition_id_fkey FOREIGN KEY (competition_id) REFERENCES championship_bracket_competitions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_bracket_tie_break_resolutions ADD CONSTRAINT championship_bracket_tie_break_resolutions_group_id_fkey FOREIGN KEY (group_id) REFERENCES championship_bracket_groups(id) ON DELETE CASCADE;
ALTER TABLE public.championship_competition_team_disqualifications ADD CONSTRAINT championship_competition_team_disqualifica_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_competition_team_disqualifications ADD CONSTRAINT championship_competition_team_disqualifications_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_competition_team_disqualifications ADD CONSTRAINT championship_competition_team_disqualifications_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES championship_award_players(id) ON DELETE SET NULL;
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_event_id_fkey FOREIGN KEY (event_id) REFERENCES championship_individual_events(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_event_entry_members ADD CONSTRAINT championship_individual_event_entry_members_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES championship_award_players(id) ON DELETE SET NULL;
ALTER TABLE public.championship_individual_event_entry_members ADD CONSTRAINT championship_individual_event_entry_members_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES championship_individual_event_entries(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_events ADD CONSTRAINT championship_individual_events_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_events ADD CONSTRAINT championship_individual_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES championship_individual_sessions(id) ON DELETE SET NULL;
ALTER TABLE public.championship_individual_events ADD CONSTRAINT championship_individual_events_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_sessions ADD CONSTRAINT championship_individual_sessions_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_sessions ADD CONSTRAINT championship_individual_sessions_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_team_standings ADD CONSTRAINT championship_individual_team_standings_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_team_standings ADD CONSTRAINT championship_individual_team_standings_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_individual_team_standings ADD CONSTRAINT championship_individual_team_standings_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_interlaje_individual_tie_break_resolutions ADD CONSTRAINT championship_interlaje_individual_tie_break_resol_event_id_fkey FOREIGN KEY (event_id) REFERENCES championship_individual_events(id) ON DELETE CASCADE;
ALTER TABLE public.championship_interlaje_ranking_audits ADD CONSTRAINT championship_interlaje_ranking_audits_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_interlaje_ranking_audits ADD CONSTRAINT championship_interlaje_ranking_audits_competition_id_fkey FOREIGN KEY (competition_id) REFERENCES championship_bracket_competitions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_break_resolutio_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_break_resolutions_group_id_fkey FOREIGN KEY (group_id) REFERENCES championship_bracket_groups(id) ON DELETE CASCADE;
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_break_resolutions_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_break_resolutions_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_knockout_result_corrections ADD CONSTRAINT championship_knockout_result_corr_corrected_winner_team_id_fkey FOREIGN KEY (corrected_winner_team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.championship_knockout_result_corrections ADD CONSTRAINT championship_knockout_result_corre_previous_winner_team_id_fkey FOREIGN KEY (previous_winner_team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.championship_knockout_result_corrections ADD CONSTRAINT championship_knockout_result_corre_source_bracket_match_id_fkey FOREIGN KEY (source_bracket_match_id) REFERENCES championship_bracket_matches(id) ON DELETE RESTRICT;
ALTER TABLE public.championship_knockout_result_corrections ADD CONSTRAINT championship_knockout_result_corrections_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_knockout_result_corrections ADD CONSTRAINT championship_knockout_result_corrections_competition_id_fkey FOREIGN KEY (competition_id) REFERENCES championship_bracket_competitions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_knockout_result_corrections ADD CONSTRAINT championship_knockout_result_corrections_source_match_id_fkey FOREIGN KEY (source_match_id) REFERENCES matches(id) ON DELETE RESTRICT;
ALTER TABLE public.championship_opening_ceremony_bonus_settings ADD CONSTRAINT championship_opening_ceremony_bonus_settin_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_overall_competition_placements ADD CONSTRAINT championship_overall_competition_placement_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_overall_competition_placements ADD CONSTRAINT championship_overall_competition_placements_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_overall_competition_placements ADD CONSTRAINT championship_overall_competition_placements_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_overall_position_point_settings ADD CONSTRAINT championship_overall_position_point_settin_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_overall_score_adjustments ADD CONSTRAINT championship_overall_score_adjustments_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_overall_score_adjustments ADD CONSTRAINT championship_overall_score_adjustments_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_overall_tie_break_resolution_teams ADD CONSTRAINT championship_overall_tie_break_resolution_te_resolution_id_fkey FOREIGN KEY (resolution_id) REFERENCES championship_overall_tie_break_resolutions(id) ON DELETE CASCADE;
ALTER TABLE public.championship_overall_tie_break_resolution_teams ADD CONSTRAINT championship_overall_tie_break_resolution_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_overall_tie_break_resolutions ADD CONSTRAINT championship_overall_tie_break_resolutions_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_season_division_movements ADD CONSTRAINT championship_season_division_movements_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_season_division_movements ADD CONSTRAINT championship_season_division_movements_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_season_settings ADD CONSTRAINT championship_season_settings_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_season_sport_removals ADD CONSTRAINT championship_season_sport_removals_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_season_sport_removals ADD CONSTRAINT championship_season_sport_removals_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE RESTRICT;
ALTER TABLE public.championship_sports ADD CONSTRAINT championship_sports_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_sports ADD CONSTRAINT championship_sports_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.championship_walkover_penalty_counts ADD CONSTRAINT championship_walkover_penalty_counts_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.championship_walkover_penalty_counts ADD CONSTRAINT championship_walkover_penalty_counts_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.championship_walkover_penalty_settings ADD CONSTRAINT championship_walkover_penalty_settings_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE CASCADE;
ALTER TABLE public.league_event_organizer_teams ADD CONSTRAINT league_event_organizer_teams_event_id_fkey FOREIGN KEY (event_id) REFERENCES league_events(id) ON DELETE CASCADE;
ALTER TABLE public.league_event_organizer_teams ADD CONSTRAINT league_event_organizer_teams_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE RESTRICT;
ALTER TABLE public.league_event_reservation_requests ADD CONSTRAINT league_event_reservation_requests_approved_league_event_id_fkey FOREIGN KEY (approved_league_event_id) REFERENCES league_events(id) ON DELETE SET NULL;
ALTER TABLE public.league_event_reservation_requests ADD CONSTRAINT league_event_reservation_requests_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE RESTRICT;
ALTER TABLE public.league_events ADD CONSTRAINT league_events_organizer_team_id_fkey FOREIGN KEY (organizer_team_id) REFERENCES teams(id) ON DELETE RESTRICT;
ALTER TABLE public.match_award_goal_scorers ADD CONSTRAINT match_award_goal_scorers_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
ALTER TABLE public.match_award_goal_scorers ADD CONSTRAINT match_award_goal_scorers_player_id_fkey FOREIGN KEY (player_id) REFERENCES championship_award_players(id) ON DELETE RESTRICT;
ALTER TABLE public.match_award_goal_scorers ADD CONSTRAINT match_award_goal_scorers_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE RESTRICT;
ALTER TABLE public.match_blue_card_players ADD CONSTRAINT match_blue_card_players_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
ALTER TABLE public.match_blue_card_players ADD CONSTRAINT match_blue_card_players_player_id_fkey FOREIGN KEY (player_id) REFERENCES championship_award_players(id) ON DELETE RESTRICT;
ALTER TABLE public.match_blue_card_players ADD CONSTRAINT match_blue_card_players_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE RESTRICT;
ALTER TABLE public.match_red_card_players ADD CONSTRAINT match_red_card_players_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
ALTER TABLE public.match_red_card_players ADD CONSTRAINT match_red_card_players_player_id_fkey FOREIGN KEY (player_id) REFERENCES championship_award_players(id) ON DELETE RESTRICT;
ALTER TABLE public.match_red_card_players ADD CONSTRAINT match_red_card_players_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE RESTRICT;
ALTER TABLE public.match_sets ADD CONSTRAINT match_sets_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
ALTER TABLE public.match_yellow_card_players ADD CONSTRAINT match_yellow_card_players_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
ALTER TABLE public.match_yellow_card_players ADD CONSTRAINT match_yellow_card_players_player_id_fkey FOREIGN KEY (player_id) REFERENCES championship_award_players(id) ON DELETE RESTRICT;
ALTER TABLE public.match_yellow_card_players ADD CONSTRAINT match_yellow_card_players_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE RESTRICT;
ALTER TABLE public.matches ADD CONSTRAINT matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.matches ADD CONSTRAINT matches_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE RESTRICT;
ALTER TABLE public.matches ADD CONSTRAINT matches_disqualification_id_fkey FOREIGN KEY (disqualification_id) REFERENCES championship_competition_team_disqualifications(id) ON DELETE SET NULL;
ALTER TABLE public.matches ADD CONSTRAINT matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE public.matches ADD CONSTRAINT matches_resolved_tie_break_winner_team_id_fkey FOREIGN KEY (resolved_tie_break_winner_team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.matches ADD CONSTRAINT matches_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.matches ADD CONSTRAINT matches_walkover_loser_team_id_fkey FOREIGN KEY (walkover_loser_team_id) REFERENCES teams(id) ON DELETE SET NULL;
ALTER TABLE public.public_link_item_filters ADD CONSTRAINT public_link_item_filters_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE RESTRICT;
ALTER TABLE public.public_link_item_filters ADD CONSTRAINT public_link_item_filters_public_link_item_id_fkey FOREIGN KEY (public_link_item_id) REFERENCES public_link_items(id) ON DELETE CASCADE;
ALTER TABLE public.public_link_items ADD CONSTRAINT public_link_items_section_id_fkey FOREIGN KEY (section_id) REFERENCES public_link_sections(id) ON DELETE RESTRICT;
ALTER TABLE public.standings ADD CONSTRAINT standings_championship_id_fkey FOREIGN KEY (championship_id) REFERENCES championships(id) ON DELETE RESTRICT;
ALTER TABLE public.standings ADD CONSTRAINT standings_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES sports(id) ON DELETE CASCADE;
ALTER TABLE public.standings ADD CONSTRAINT standings_team_id_fkey FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE;
