-- LAJE-112 — índices standalone do schema public.
-- Índices gerados implicitamente por PK/UNIQUE ficam em constraints.sql.

CREATE INDEX admin_action_logs_action_type_idx ON public.admin_action_logs USING btree (action_type);
CREATE INDEX admin_action_logs_actor_user_id_idx ON public.admin_action_logs USING btree (actor_user_id);
CREATE INDEX admin_action_logs_created_at_idx ON public.admin_action_logs USING btree (created_at DESC);
CREATE INDEX admin_action_logs_resource_table_idx ON public.admin_action_logs USING btree (resource_table);
CREATE INDEX admin_profile_permissions_admin_tab_idx ON public.admin_profile_permissions USING btree (admin_tab);
CREATE UNIQUE INDEX admin_profiles_name_unique_idx ON public.admin_profiles USING btree (lower(name));
CREATE UNIQUE INDEX admin_profiles_system_role_unique_idx ON public.admin_profiles USING btree (system_role) WHERE (system_role IS NOT NULL);
CREATE UNIQUE INDEX admin_user_profiles_login_identifier_uidx ON public.admin_user_profiles USING btree (lower(login_identifier));
CREATE INDEX admin_user_profiles_profile_id_idx ON public.admin_user_profiles USING btree (profile_id);
CREATE INDEX championship_award_players_scope_idx ON public.championship_award_players USING btree (championship_id, season_year, sport_id, naipe, division, team_id);
CREATE UNIQUE INDEX championship_award_players_unique_with_division_idx ON public.championship_award_players USING btree (championship_id, season_year, sport_id, team_id, naipe, division, normalized_name) WHERE (division IS NOT NULL);
CREATE UNIQUE INDEX championship_award_players_unique_without_division_idx ON public.championship_award_players USING btree (championship_id, season_year, sport_id, team_id, naipe, normalized_name) WHERE (division IS NULL);
CREATE UNIQUE INDEX championship_bracket_competitions_upsert_uidx ON public.championship_bracket_competitions USING btree (bracket_edition_id, sport_id, naipe, division);
CREATE UNIQUE INDEX championship_bracket_court_sports_upsert_uidx ON public.championship_bracket_court_sports USING btree (bracket_court_id, sport_id);
CREATE INDEX championship_bracket_courts_court_group_idx ON public.championship_bracket_courts USING btree (court_group_id);
CREATE INDEX championship_bracket_courts_preferred_sport_idx ON public.championship_bracket_courts USING btree (preferred_sport_id) WHERE (preferred_sport_id IS NOT NULL);
CREATE UNIQUE INDEX championship_bracket_courts_upsert_uidx ON public.championship_bracket_courts USING btree (bracket_location_id, name);
CREATE INDEX championship_bracket_day_breaks_scope_idx ON public.championship_bracket_day_breaks USING btree (bracket_day_id, scope_type, bracket_court_id, "position");
CREATE UNIQUE INDEX championship_bracket_days_upsert_uidx ON public.championship_bracket_days USING btree (bracket_edition_id, event_date);
CREATE INDEX championship_bracket_editions_championship_id_idx ON public.championship_bracket_editions USING btree (championship_id);
CREATE INDEX championship_bracket_editions_championship_season_year_created_ ON public.championship_bracket_editions USING btree (championship_id, season_year, created_at DESC);
CREATE UNIQUE INDEX championship_bracket_editions_unique_draft_by_championship_and_ ON public.championship_bracket_editions USING btree (championship_id, season_year) WHERE (status = 'DRAFT'::bracket_edition_status);
CREATE UNIQUE INDEX championship_bracket_group_teams_upsert_uidx ON public.championship_bracket_group_teams USING btree (group_id, team_id);
CREATE UNIQUE INDEX championship_bracket_groups_upsert_uidx ON public.championship_bracket_groups USING btree (competition_id, group_number);
CREATE INDEX championship_bracket_knockout_court_priorities_lookup_idx ON public.championship_bracket_knockout_court_priorities USING btree (bracket_edition_id, sport_id, phase, division_scope);
CREATE INDEX cb_ko_schedule_reservation_competition_idx ON public.championship_bracket_knockout_schedule_reservations USING btree (competition_id, round_number, slot_number);
CREATE INDEX cb_ko_schedule_reservation_court_time_idx ON public.championship_bracket_knockout_schedule_reservations USING btree (bracket_edition_id, scheduled_date, bracket_court_id, start_at, end_at);
CREATE INDEX cb_ko_schedule_reservation_edition_idx ON public.championship_bracket_knockout_schedule_reservations USING btree (bracket_edition_id);
CREATE INDEX championship_bracket_location_sport_priorities_lookup_idx ON public.championship_bracket_location_sport_priorities USING btree (bracket_edition_id, location_group_id, sport_id);
CREATE UNIQUE INDEX championship_bracket_location_template_court_sports_court_sport ON public.championship_bracket_location_template_court_sports USING btree (location_template_court_id, sport_id);
CREATE UNIQUE INDEX championship_bracket_location_template_courts_template_name_uid ON public.championship_bracket_location_template_courts USING btree (location_template_id, name);
CREATE UNIQUE INDEX championship_bracket_location_templates_normalized_name_uidx ON public.championship_bracket_location_templates USING btree (normalized_name);
CREATE INDEX championship_bracket_locations_location_group_idx ON public.championship_bracket_locations USING btree (location_group_id);
CREATE UNIQUE INDEX championship_bracket_locations_upsert_uidx ON public.championship_bracket_locations USING btree (bracket_day_id, name);
CREATE INDEX championship_bracket_matches_edition_phase_idx ON public.championship_bracket_matches USING btree (bracket_edition_id, phase);
CREATE INDEX championship_bracket_team_modalities_competition_idx ON public.championship_bracket_team_modalities USING btree (bracket_edition_id, sport_id, naipe, division);
CREATE UNIQUE INDEX championship_bracket_team_modalities_upsert_uidx ON public.championship_bracket_team_modalities USING btree (bracket_edition_id, team_id, sport_id, naipe, division);
CREATE UNIQUE INDEX championship_bracket_team_registrations_upsert_uidx ON public.championship_bracket_team_registrations USING btree (bracket_edition_id, team_id);
CREATE UNIQUE INDEX championship_bracket_tie_break_resolution_teams_resolution_orde ON public.championship_bracket_tie_break_resolution_teams USING btree (resolution_id, draw_order);
CREATE UNIQUE INDEX championship_bracket_tie_break_resolution_teams_resolution_team ON public.championship_bracket_tie_break_resolution_teams USING btree (resolution_id, team_id);
CREATE UNIQUE INDEX championship_bracket_tie_break_resolutions_context_key_uidx ON public.championship_bracket_tie_break_resolutions USING btree (context_key);
CREATE INDEX championship_competition_team_disqualifications_lookup_idx ON public.championship_competition_team_disqualifications USING btree (championship_id, season_year, sport_id, naipe, division, team_id);
CREATE INDEX championship_individual_entries_event_idx ON public.championship_individual_event_entries USING btree (event_id, team_id, status, final_position);
CREATE UNIQUE INDEX championship_individual_event_entries_unique_athlete_idx ON public.championship_individual_event_entries USING btree (event_id, athlete_id) WHERE (athlete_id IS NOT NULL);
CREATE UNIQUE INDEX championship_individual_event_entries_unique_legacy_relay_team_ ON public.championship_individual_event_entries USING btree (event_id, team_id) WHERE ((entry_type = 'RELAY'::championship_individual_event_kind) AND (recording_mode = 'ATHLETE_METRIC'::text));
CREATE UNIQUE INDEX championship_individual_event_entries_unique_manual_lane_idx ON public.championship_individual_event_entries USING btree (event_id, team_id, lane_number) WHERE (lane_number IS NOT NULL);
CREATE UNIQUE INDEX championship_individual_event_entries_unique_team_placement_pos ON public.championship_individual_event_entries USING btree (event_id, final_position) WHERE ((recording_mode = 'TEAM_PLACEMENT'::text) AND (status = 'CONFIRMED'::championship_individual_entry_status));
CREATE UNIQUE INDEX championship_individual_event_entries_unique_team_placement_wal ON public.championship_individual_event_entries USING btree (event_id, team_id) WHERE ((recording_mode = 'TEAM_PLACEMENT'::text) AND (status = 'WALKOVER'::championship_individual_entry_status));
CREATE UNIQUE INDEX championship_individual_event_entry_members_unique_athlete_idx ON public.championship_individual_event_entry_members USING btree (entry_id, athlete_id) WHERE (athlete_id IS NOT NULL);
CREATE INDEX championship_individual_members_entry_idx ON public.championship_individual_event_entry_members USING btree (entry_id, is_starter, "position");
CREATE INDEX championship_individual_events_lookup_idx ON public.championship_individual_events USING btree (championship_id, season_year, sport_id, naipe, division, status, scheduled_date);
CREATE INDEX championship_individual_events_session_idx ON public.championship_individual_events USING btree (session_id);
CREATE INDEX championship_individual_sessions_championship_lookup_idx ON public.championship_individual_sessions USING btree (championship_id, season_year, sport_id, naipe, division);
CREATE INDEX championship_individual_team_standings_lookup_idx ON public.championship_individual_team_standings USING btree (championship_id, season_year, sport_id, naipe, division, total_points DESC);
CREATE INDEX championship_knockout_result_corrections_source_match_idx ON public.championship_knockout_result_corrections USING btree (source_match_id, created_at DESC);
CREATE INDEX championship_opening_ceremony_bonus_settings_championship_year_ ON public.championship_opening_ceremony_bonus_settings USING btree (championship_id, season_year DESC);
CREATE INDEX championship_overall_position_point_settings_scope_idx ON public.championship_overall_position_point_settings USING btree (championship_id, season_year, final_position);
CREATE INDEX championship_season_division_movements_championship_year_idx ON public.championship_season_division_movements USING btree (championship_id, season_year DESC, ranking_position);
CREATE INDEX championship_season_settings_championship_year_idx ON public.championship_season_settings USING btree (championship_id, season_year DESC);
CREATE INDEX championship_season_sport_removals_lookup_idx ON public.championship_season_sport_removals USING btree (championship_id, season_year, sport_id);
CREATE UNIQUE INDEX championship_sports_championship_id_sport_id_unique_idx ON public.championship_sports USING btree (championship_id, sport_id);
CREATE INDEX championship_walkover_penalty_counts_championship_year_idx ON public.championship_walkover_penalty_counts USING btree (championship_id, season_year DESC);
CREATE UNIQUE INDEX championships_code_unique_idx ON public.championships USING btree (code);
CREATE INDEX league_calendar_holidays_date_idx ON public.league_calendar_holidays USING btree (holiday_date);
CREATE UNIQUE INDEX league_calendar_holidays_unique_day_idx ON public.league_calendar_holidays USING btree (holiday_date, name, scope, day_kind);
CREATE INDEX league_event_organizer_teams_team_id_idx ON public.league_event_organizer_teams USING btree (team_id);
CREATE INDEX league_event_reservation_requests_event_date_idx ON public.league_event_reservation_requests USING btree (event_date);
CREATE INDEX league_event_reservation_requests_status_idx ON public.league_event_reservation_requests USING btree (status);
CREATE INDEX league_event_reservation_requests_team_id_idx ON public.league_event_reservation_requests USING btree (team_id);
CREATE INDEX league_events_event_date_idx ON public.league_events USING btree (event_date);
CREATE INDEX match_award_goal_scorers_match_idx ON public.match_award_goal_scorers USING btree (match_id);
CREATE INDEX match_blue_card_players_match_idx ON public.match_blue_card_players USING btree (match_id);
CREATE INDEX match_blue_card_players_player_idx ON public.match_blue_card_players USING btree (player_id);
CREATE INDEX match_red_card_players_match_idx ON public.match_red_card_players USING btree (match_id);
CREATE INDEX match_red_card_players_player_idx ON public.match_red_card_players USING btree (player_id);
CREATE INDEX match_yellow_card_players_match_idx ON public.match_yellow_card_players USING btree (match_id);
CREATE INDEX match_yellow_card_players_player_idx ON public.match_yellow_card_players USING btree (player_id);
CREATE INDEX matches_championship_season_away_team_idx ON public.matches USING btree (championship_id, season_year, away_team_id, sport_id, naipe, division);
CREATE INDEX matches_championship_season_home_team_idx ON public.matches USING btree (championship_id, season_year, home_team_id, sport_id, naipe, division);
CREATE UNIQUE INDEX matches_championship_season_year_queue_position_uidx ON public.matches USING btree (championship_id, season_year, scheduled_date, sport_id, naipe, coerce_division_for_index(division), queue_position) WHERE ((scheduled_date IS NOT NULL) AND (queue_position IS NOT NULL));
CREATE INDEX matches_championship_season_year_scheduled_date_idx ON public.matches USING btree (championship_id, season_year, scheduled_date, queue_position);
CREATE INDEX matches_disqualification_id_idx ON public.matches USING btree (disqualification_id) WHERE (disqualification_id IS NOT NULL);
CREATE INDEX matches_scheduled_slot_idx ON public.matches USING btree (championship_id, season_year, scheduled_date, scheduled_slot) WHERE (scheduled_slot IS NOT NULL);
CREATE INDEX public_link_item_filters_championship_year_idx ON public.public_link_item_filters USING btree (championship_id, season_year);
CREATE INDEX public_link_item_filters_item_idx ON public.public_link_item_filters USING btree (public_link_item_id);
CREATE INDEX public_link_items_filter_mode_idx ON public.public_link_items USING btree (filter_mode);
CREATE INDEX public_link_items_section_sort_order_idx ON public.public_link_items USING btree (section_id, sort_order, created_at);
CREATE INDEX public_link_sections_sort_order_idx ON public.public_link_sections USING btree (sort_order, created_at);
CREATE UNIQUE INDEX sports_code_key ON public.sports USING btree (code) WHERE (code IS NOT NULL);
CREATE UNIQUE INDEX standings_champ_season_sport_naipe_team_division_uidx ON public.standings USING btree (championship_id, season_year, sport_id, naipe, team_id, division) WHERE (division IS NOT NULL);
CREATE UNIQUE INDEX standings_champ_season_sport_naipe_team_without_division_uidx ON public.standings USING btree (championship_id, season_year, sport_id, naipe, team_id) WHERE (division IS NULL);
CREATE INDEX standings_championship_season_lookup_idx ON public.standings USING btree (championship_id, season_year, sport_id, naipe, division, team_id);
