-- LAJE-112 — primary keys e constraints UNIQUE do schema public.

ALTER TABLE public.admin_action_logs ADD CONSTRAINT admin_action_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.admin_profile_permissions ADD CONSTRAINT admin_profile_permissions_pkey PRIMARY KEY (profile_id, admin_tab);
ALTER TABLE public.admin_profiles ADD CONSTRAINT admin_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.admin_user_profiles ADD CONSTRAINT admin_user_profiles_pkey PRIMARY KEY (user_id);
ALTER TABLE public.championship_award_draw_results ADD CONSTRAINT championship_award_draw_results_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_award_players ADD CONSTRAINT championship_award_players_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_competitions ADD CONSTRAINT championship_bracket_competitions_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_court_sports ADD CONSTRAINT championship_bracket_court_sports_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_courts ADD CONSTRAINT championship_bracket_courts_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_day_breaks ADD CONSTRAINT championship_bracket_day_breaks_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_days ADD CONSTRAINT championship_bracket_days_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_editions ADD CONSTRAINT championship_bracket_editions_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_group_teams ADD CONSTRAINT championship_bracket_group_teams_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_groups ADD CONSTRAINT championship_bracket_groups_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_knockout_court_priorities ADD CONSTRAINT championship_bracket_knockout_court_priorities_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT championship_bracket_knockout_schedule_reservations_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_location_sport_priorities ADD CONSTRAINT championship_bracket_location_sport_priorities_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_location_template_court_sports ADD CONSTRAINT championship_bracket_location_template_court_sports_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_location_template_courts ADD CONSTRAINT championship_bracket_location_template_courts_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_location_templates ADD CONSTRAINT championship_bracket_location_templates_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_locations ADD CONSTRAINT championship_bracket_locations_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_team_modalities ADD CONSTRAINT championship_bracket_team_modalities_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_team_registrations ADD CONSTRAINT championship_bracket_team_registrations_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_tie_break_resolution_teams ADD CONSTRAINT championship_bracket_tie_break_resolution_teams_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_bracket_tie_break_resolutions ADD CONSTRAINT championship_bracket_tie_break_resolutions_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_competition_team_disqualifications ADD CONSTRAINT championship_competition_team_disqualifications_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_individual_event_entries ADD CONSTRAINT championship_individual_event_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_individual_event_entry_members ADD CONSTRAINT championship_individual_event_entry_members_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_individual_events ADD CONSTRAINT championship_individual_events_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_individual_sessions ADD CONSTRAINT championship_individual_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_individual_team_standings ADD CONSTRAINT championship_individual_team_standings_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_interlaje_individual_tie_break_resolutions ADD CONSTRAINT championship_interlaje_individual_tie_break_resolutions_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_interlaje_ranking_audits ADD CONSTRAINT championship_interlaje_ranking_audits_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_break_resolutions_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_knockout_result_corrections ADD CONSTRAINT championship_knockout_result_corrections_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_opening_ceremony_bonus_settings ADD CONSTRAINT championship_opening_ceremony_bonus_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_overall_competition_placements ADD CONSTRAINT championship_overall_competition_placements_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_overall_position_point_settings ADD CONSTRAINT championship_overall_position_point_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_overall_score_adjustments ADD CONSTRAINT championship_overall_score_adjustments_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_overall_tie_break_resolution_teams ADD CONSTRAINT championship_overall_tie_break_resolution_teams_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_overall_tie_break_resolutions ADD CONSTRAINT championship_overall_tie_break_resolutions_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_season_division_movements ADD CONSTRAINT championship_season_division_movements_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_season_settings ADD CONSTRAINT championship_season_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_season_sport_removals ADD CONSTRAINT championship_season_sport_removals_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_sports ADD CONSTRAINT championship_sports_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_walkover_penalty_counts ADD CONSTRAINT championship_walkover_penalty_counts_pkey PRIMARY KEY (id);
ALTER TABLE public.championship_walkover_penalty_settings ADD CONSTRAINT championship_walkover_penalty_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.championships ADD CONSTRAINT championships_pkey PRIMARY KEY (id);
ALTER TABLE public.league_calendar_holidays ADD CONSTRAINT league_calendar_holidays_pkey PRIMARY KEY (id);
ALTER TABLE public.league_event_organizer_teams ADD CONSTRAINT league_event_organizer_teams_pkey PRIMARY KEY (event_id, team_id);
ALTER TABLE public.league_event_reservation_requests ADD CONSTRAINT league_event_reservation_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.league_events ADD CONSTRAINT league_events_pkey PRIMARY KEY (id);
ALTER TABLE public.match_award_goal_scorers ADD CONSTRAINT match_award_goal_scorers_pkey PRIMARY KEY (id);
ALTER TABLE public.match_blue_card_players ADD CONSTRAINT match_blue_card_players_pkey PRIMARY KEY (id);
ALTER TABLE public.match_red_card_players ADD CONSTRAINT match_red_card_players_pkey PRIMARY KEY (id);
ALTER TABLE public.match_sets ADD CONSTRAINT match_sets_pkey PRIMARY KEY (id);
ALTER TABLE public.match_yellow_card_players ADD CONSTRAINT match_yellow_card_players_pkey PRIMARY KEY (id);
ALTER TABLE public.matches ADD CONSTRAINT matches_pkey PRIMARY KEY (id);
ALTER TABLE public.public_link_item_filters ADD CONSTRAINT public_link_item_filters_pkey PRIMARY KEY (id);
ALTER TABLE public.public_link_items ADD CONSTRAINT public_link_items_pkey PRIMARY KEY (id);
ALTER TABLE public.public_link_sections ADD CONSTRAINT public_link_sections_pkey PRIMARY KEY (id);
ALTER TABLE public.public_page_access_settings ADD CONSTRAINT public_page_access_settings_pkey PRIMARY KEY (id);
ALTER TABLE public.sports ADD CONSTRAINT sports_pkey PRIMARY KEY (id);
ALTER TABLE public.standings ADD CONSTRAINT standings_pkey PRIMARY KEY (id);
ALTER TABLE public.teams ADD CONSTRAINT teams_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);

ALTER TABLE public.championship_award_draw_results ADD CONSTRAINT championship_award_draw_results_unique UNIQUE (championship_id, season_year, sport_id, naipe, division, award_type);
ALTER TABLE public.championship_bracket_competitions ADD CONSTRAINT championship_bracket_competitions_upsert_unique UNIQUE (bracket_edition_id, sport_id, naipe, division);
ALTER TABLE public.championship_bracket_court_sports ADD CONSTRAINT championship_bracket_court_sports_upsert_unique UNIQUE (bracket_court_id, sport_id);
ALTER TABLE public.championship_bracket_courts ADD CONSTRAINT championship_bracket_courts_upsert_unique UNIQUE (bracket_location_id, name);
ALTER TABLE public.championship_bracket_day_breaks ADD CONSTRAINT championship_bracket_day_breaks_bracket_day_id_position_key UNIQUE (bracket_day_id, "position");
ALTER TABLE public.championship_bracket_days ADD CONSTRAINT championship_bracket_days_upsert_unique UNIQUE (bracket_edition_id, event_date);
ALTER TABLE public.championship_bracket_group_teams ADD CONSTRAINT championship_bracket_group_teams_group_id_position_key UNIQUE (group_id, "position");
ALTER TABLE public.championship_bracket_group_teams ADD CONSTRAINT championship_bracket_group_teams_upsert_unique UNIQUE (group_id, team_id);
ALTER TABLE public.championship_bracket_groups ADD CONSTRAINT championship_bracket_groups_upsert_unique UNIQUE (competition_id, group_number);
ALTER TABLE public.championship_bracket_knockout_court_priorities ADD CONSTRAINT championship_bracket_knockout_bracket_edition_id_sport_id_p_key UNIQUE (bracket_edition_id, sport_id, phase, division_scope);
ALTER TABLE public.championship_bracket_knockout_schedule_reservations ADD CONSTRAINT cb_ko_schedule_reservation_unique UNIQUE (competition_id, round_number, slot_number);
ALTER TABLE public.championship_bracket_location_sport_priorities ADD CONSTRAINT championship_bracket_location_bracket_edition_id_location_g_key UNIQUE (bracket_edition_id, location_group_id, sport_id);
ALTER TABLE public.championship_bracket_locations ADD CONSTRAINT championship_bracket_locations_upsert_unique UNIQUE (bracket_day_id, name);
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_competition_id_phase_round_num_key UNIQUE (competition_id, phase, round_number, slot_number);
ALTER TABLE public.championship_bracket_matches ADD CONSTRAINT championship_bracket_matches_match_id_key UNIQUE (match_id);
ALTER TABLE public.championship_bracket_team_modalities ADD CONSTRAINT championship_bracket_team_modalities_upsert_unique UNIQUE (bracket_edition_id, team_id, sport_id, naipe, division);
ALTER TABLE public.championship_bracket_team_registrations ADD CONSTRAINT championship_bracket_team_registrations_upsert_unique UNIQUE (bracket_edition_id, team_id);
ALTER TABLE public.championship_competition_team_disqualifications ADD CONSTRAINT championship_competition_team_championship_id_season_year_s_key UNIQUE (championship_id, season_year, sport_id, naipe, division, team_id);
ALTER TABLE public.championship_individual_events ADD CONSTRAINT championship_individual_events_unique_context UNIQUE (championship_id, season_year, sport_id, naipe, division, event_code);
ALTER TABLE public.championship_individual_sessions ADD CONSTRAINT championship_individual_sessions_unique_scope UNIQUE NULLS NOT DISTINCT (championship_id, season_year, sport_id, naipe, division);
ALTER TABLE public.championship_individual_team_standings ADD CONSTRAINT championship_individual_team_standings_unique_context UNIQUE (championship_id, season_year, sport_id, naipe, division, team_id);
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_br_championship_id_season_year__key1 UNIQUE NULLS NOT DISTINCT (championship_id, season_year, sport_id, naipe, division, group_id, draw_order);
ALTER TABLE public.championship_interlaje_tie_break_resolutions ADD CONSTRAINT championship_interlaje_tie_br_championship_id_season_year_s_key UNIQUE NULLS NOT DISTINCT (championship_id, season_year, sport_id, naipe, division, group_id, team_id);
ALTER TABLE public.championship_opening_ceremony_bonus_settings ADD CONSTRAINT championship_opening_ceremony_b_championship_id_season_year_key UNIQUE (championship_id, season_year);
ALTER TABLE public.championship_overall_competition_placements ADD CONSTRAINT championship_overall_competition_placements_position_key UNIQUE NULLS NOT DISTINCT (championship_id, season_year, sport_id, naipe, division, final_position);
ALTER TABLE public.championship_overall_competition_placements ADD CONSTRAINT championship_overall_competition_placements_team_key UNIQUE NULLS NOT DISTINCT (championship_id, season_year, sport_id, naipe, division, team_id);
ALTER TABLE public.championship_overall_position_point_settings ADD CONSTRAINT championship_overall_position_championship_id_season_year_f_key UNIQUE (championship_id, season_year, final_position);
ALTER TABLE public.championship_overall_score_adjustments ADD CONSTRAINT championship_overall_score_ad_championship_id_season_year_t_key UNIQUE (championship_id, season_year, team_id, adjustment_type);
ALTER TABLE public.championship_overall_tie_break_resolution_teams ADD CONSTRAINT championship_overall_tie_break_res_resolution_id_draw_order_key UNIQUE (resolution_id, draw_order);
ALTER TABLE public.championship_overall_tie_break_resolution_teams ADD CONSTRAINT championship_overall_tie_break_resolu_resolution_id_team_id_key UNIQUE (resolution_id, team_id);
ALTER TABLE public.championship_overall_tie_break_resolutions ADD CONSTRAINT championship_overall_tie_brea_championship_id_season_year_p_key UNIQUE (championship_id, season_year, points_total, team_signature);
ALTER TABLE public.championship_season_division_movements ADD CONSTRAINT championship_season_division_movements_unique UNIQUE (championship_id, season_year, team_id);
ALTER TABLE public.championship_season_settings ADD CONSTRAINT championship_season_settings_unique UNIQUE (championship_id, season_year);
ALTER TABLE public.championship_season_sport_removals ADD CONSTRAINT championship_season_sport_rem_championship_id_season_year_s_key UNIQUE (championship_id, season_year, sport_id);
ALTER TABLE public.championship_walkover_penalty_counts ADD CONSTRAINT championship_walkover_penalty_championship_id_season_year_t_key UNIQUE (championship_id, season_year, team_id);
ALTER TABLE public.championship_walkover_penalty_settings ADD CONSTRAINT championship_walkover_penalty_s_championship_id_season_year_key UNIQUE (championship_id, season_year);
ALTER TABLE public.match_award_goal_scorers ADD CONSTRAINT match_award_goal_scorers_unique_goal_slot UNIQUE (match_id, team_id, goal_order);
ALTER TABLE public.match_blue_card_players ADD CONSTRAINT match_blue_card_players_unique_card_slot UNIQUE (match_id, team_id, card_order);
ALTER TABLE public.match_red_card_players ADD CONSTRAINT match_red_card_players_unique_card_slot UNIQUE (match_id, team_id, card_order);
ALTER TABLE public.match_red_card_players ADD CONSTRAINT match_red_card_players_unique_player UNIQUE (match_id, team_id, player_id);
ALTER TABLE public.match_sets ADD CONSTRAINT match_sets_match_id_set_number_key UNIQUE (match_id, set_number);
ALTER TABLE public.match_yellow_card_players ADD CONSTRAINT match_yellow_card_players_unique_card_slot UNIQUE (match_id, team_id, card_order);
ALTER TABLE public.public_link_item_filters ADD CONSTRAINT public_link_item_filters_unique UNIQUE (public_link_item_id, championship_id, season_year);
ALTER TABLE public.sports ADD CONSTRAINT sports_name_key UNIQUE (name);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
