const implemented = "implemented" as const;
const json = (schema: unknown) => ({ "application/json": { schema } });
const success = (schema: unknown, description = "Operação concluída.") => ({
  description,
  content: json(schema),
});
const error = (description: string) => ({
  description,
  content: json({ $ref: "#/components/schemas/ApiError" }),
});
const bearer = [{ bearerAuth: [] }];
const championshipId = {
  name: "championshipId",
  in: "path",
  required: true,
  schema: { type: "string", format: "uuid" },
};
const matchId = {
  name: "matchId",
  in: "path",
  required: true,
  schema: { type: "string", format: "uuid" },
};
const seasonYearPath = {
  name: "seasonYear",
  in: "path",
  required: true,
  schema: { type: "integer", minimum: 2000, maximum: 2100 },
};
const seasonYearQuery = {
  name: "seasonYear",
  in: "query",
  required: true,
  schema: { type: "integer", minimum: 2000, maximum: 2100 },
};
const nonNegativeInteger = { type: "integer", minimum: 0 } as const;
const nullableString = { type: ["string", "null"] } as const;
const nullableUuid = { type: ["string", "null"], format: "uuid" } as const;

export const sportsCoreTags = [
  { name: "Brackets", description: "Estrutura e geração das chaves esportivas." },
  { name: "Seasons", description: "Configuração operacional das temporadas de campeonatos." },
];

export const sportsCorePaths = {
  "/api/v1/matches": {
    get: {
      tags: ["Matches"],
      summary: "Lista jogos do núcleo esportivo",
      operationId: "listMatches",
      "x-implementation-status": implemented,
      parameters: [
        { name: "championshipId", in: "query", schema: { type: "string", format: "uuid" } },
        {
          name: "seasonYear",
          in: "query",
          schema: { type: "integer", minimum: 2000, maximum: 2100 },
        },
        {
          name: "status",
          in: "query",
          style: "form",
          explode: true,
          schema: { type: "array", items: { $ref: "#/components/schemas/MatchStatus" } },
        },
        { name: "sportId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "teamId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "naipe", in: "query", schema: { $ref: "#/components/schemas/MatchNaipe" } },
        { name: "division", in: "query", schema: { $ref: "#/components/schemas/TeamDivision" } },
        {
          name: "groupNumber",
          in: "query",
          schema: { type: "integer", minimum: 1, maximum: 64 },
        },
        { name: "location", in: "query", schema: { type: "string", maxLength: 255 } },
        { name: "courtName", in: "query", schema: { type: "string", maxLength: 255 } },
        { name: "from", in: "query", schema: { type: "string", format: "date" } },
        { name: "to", in: "query", schema: { type: "string", format: "date" } },
        {
          name: "matchId",
          in: "query",
          style: "form",
          explode: true,
          description: "Um ou mais IDs de partidas. Também aceita valores separados por vírgula.",
          schema: { type: "array", items: { type: "string", format: "uuid" } },
        },
        { $ref: "#/components/parameters/Page" },
        { $ref: "#/components/parameters/PageSize" },
        {
          name: "sort",
          in: "query",
          schema: {
            type: "string",
            enum: ["scheduledDate", "queuePosition", "createdAt"],
            default: "scheduledDate",
          },
        },
        { $ref: "#/components/parameters/Order" },
      ],
      responses: {
        "200": success({
          type: "object",
          required: ["data", "meta"],
          additionalProperties: false,
          properties: {
            data: { type: "array", items: { $ref: "#/components/schemas/MatchDto" } },
            meta: { $ref: "#/components/schemas/PaginationMeta" },
          },
        }),
        "422": error("Filtros inválidos."),
      },
    },
  },
  "/api/v1/matches/{matchId}": {
    get: {
      tags: ["Matches"],
      summary: "Obtém um jogo",
      operationId: "getMatch",
      "x-implementation-status": implemented,
      parameters: [matchId],
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/MatchDto" } },
        }),
        "404": error("Jogo não encontrado."),
      },
    },
  },
  "/api/v1/matches/{matchId}/start": {
    post: {
      tags: ["Matches"],
      summary: "Inicia um jogo agendado",
      operationId: "startMatch",
      "x-implementation-status": implemented,
      security: bearer,
      parameters: [matchId],
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/MatchDto" } },
        }),
        "401": error("Sessão inválida."),
        "403": error("Permissão control:EDIT necessária."),
        "409": error("Estado do jogo incompatível."),
      },
    },
  },
  "/api/v1/matches/{matchId}/scoreboard": {
    patch: {
      tags: ["Matches"],
      summary: "Atualiza o placar operacional",
      operationId: "updateMatchScoreboard",
      "x-implementation-status": implemented,
      security: bearer,
      parameters: [matchId],
      requestBody: {
        required: true,
        content: json({ $ref: "#/components/schemas/ScoreboardUpdateRequest" }),
      },
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/MatchDto" } },
        }),
        "409": error("Jogo não está ao vivo ou sofreu atualização concorrente."),
        "422": error("Payload inválido."),
      },
    },
  },
  "/api/v1/matches/{matchId}/finish": {
    post: {
      tags: ["Matches"],
      summary: "Encerra um jogo e consolida standings",
      operationId: "finishMatch",
      "x-implementation-status": implemented,
      security: bearer,
      parameters: [matchId],
      requestBody: {
        required: false,
        content: json({ $ref: "#/components/schemas/MatchFinishRequest" }),
      },
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/MatchDto" } },
        }),
        "409": error("Jogo não está ao vivo ou sofreu atualização concorrente."),
      },
    },
  },
  "/api/v1/championships": {
    get: {
      tags: ["Championships"],
      summary: "Lista campeonatos",
      operationId: "listChampionships",
      "x-implementation-status": implemented,
      parameters: [
        { name: "status", in: "query", schema: { $ref: "#/components/schemas/ChampionshipStatus" } },
        { name: "code", in: "query", schema: { type: "string", enum: ["CLV", "SOCIETY", "INTERLAJE"] } },
      ],
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: {
            data: { type: "array", items: { $ref: "#/components/schemas/ChampionshipDto" } },
          },
        }),
      },
    },
    post: {
      tags: ["Championships"],
      summary: "Cria campeonato",
      operationId: "createChampionship",
      "x-implementation-status": implemented,
      security: bearer,
      requestBody: {
        required: true,
        content: json({ $ref: "#/components/schemas/ChampionshipWriteRequest" }),
      },
      responses: {
        "201": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/ChampionshipDto" } },
        }),
        "403": error("Permissão settings:EDIT necessária."),
      },
    },
  },
  "/api/v1/championships/{championshipId}": {
    get: {
      tags: ["Championships"],
      summary: "Obtém campeonato",
      operationId: "getChampionship",
      "x-implementation-status": implemented,
      parameters: [championshipId],
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/ChampionshipDto" } },
        }),
        "404": error("Campeonato não encontrado."),
      },
    },
    patch: {
      tags: ["Championships"],
      summary: "Atualiza campeonato",
      operationId: "updateChampionship",
      "x-implementation-status": implemented,
      security: bearer,
      parameters: [championshipId],
      requestBody: {
        required: true,
        content: json({ $ref: "#/components/schemas/ChampionshipWriteRequest" }),
      },
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/ChampionshipDto" } },
        }),
      },
    },
  },
  "/api/v1/championships/{championshipId}/seasons/{seasonYear}": {
    get: {
      tags: ["Seasons"],
      summary: "Obtém configuração da temporada",
      operationId: "getChampionshipSeason",
      "x-implementation-status": implemented,
      parameters: [championshipId, seasonYearPath],
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: {
            data: { anyOf: [{ $ref: "#/components/schemas/SeasonSettingsDto" }, { type: "null" }] },
          },
        }),
      },
    },
    put: {
      tags: ["Seasons"],
      summary: "Cria ou atualiza configuração da temporada",
      operationId: "upsertChampionshipSeason",
      "x-implementation-status": implemented,
      security: bearer,
      parameters: [championshipId, seasonYearPath],
      requestBody: {
        required: true,
        content: json({ $ref: "#/components/schemas/SeasonSettingsWriteRequest" }),
      },
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/SeasonSettingsDto" } },
        }),
      },
    },
  },
  "/api/v1/championships/{championshipId}/standings": {
    get: {
      tags: ["Standings"],
      summary: "Obtém classificação oficial ordenada pelo backend",
      operationId: "getChampionshipStandings",
      "x-implementation-status": implemented,
      parameters: [
        championshipId,
        seasonYearQuery,
        { name: "sportId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "naipe", in: "query", schema: { $ref: "#/components/schemas/MatchNaipe" } },
        { name: "division", in: "query", schema: { $ref: "#/components/schemas/TeamDivision" } },
        { $ref: "#/components/parameters/Page" },
        { $ref: "#/components/parameters/PageSize" },
      ],
      responses: {
        "200": success({
          type: "object",
          required: ["data", "meta"],
          additionalProperties: false,
          properties: {
            data: { type: "array", items: { $ref: "#/components/schemas/StandingDto" } },
            meta: { $ref: "#/components/schemas/PaginationMeta" },
          },
        }),
        "404": error("Campeonato não encontrado."),
      },
    },
  },
  "/api/v1/championships/{championshipId}/calendar": {
    get: {
      tags: ["Championships"],
      summary: "Obtém calendário público do campeonato",
      operationId: "getChampionshipCalendar",
      "x-implementation-status": implemented,
      parameters: [
        championshipId,
        seasonYearQuery,
        { name: "from", in: "query", schema: { type: "string", format: "date" } },
        { name: "to", in: "query", schema: { type: "string", format: "date" } },
        { name: "sportId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "teamId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "naipe", in: "query", schema: { $ref: "#/components/schemas/MatchNaipe" } },
        { name: "division", in: "query", schema: { $ref: "#/components/schemas/TeamDivision" } },
        { $ref: "#/components/parameters/Page" },
        { $ref: "#/components/parameters/PageSize" },
      ],
      responses: {
        "200": success({
          type: "object",
          required: ["data", "meta"],
          additionalProperties: false,
          properties: {
            data: { type: "array", items: { $ref: "#/components/schemas/CalendarMatchDto" } },
            meta: { $ref: "#/components/schemas/PaginationMeta" },
          },
        }),
        "404": error("Campeonato não encontrado."),
        "422": error("Filtros inválidos."),
      },
    },
  },
  "/api/v1/championships/{championshipId}/bracket": {
    get: {
      tags: ["Brackets"],
      summary: "Consulta a chave vigente",
      operationId: "getChampionshipBracket",
      "x-implementation-status": implemented,
      parameters: [championshipId, seasonYearQuery],
      responses: {
        "200": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/BracketViewDto" } },
        }),
      },
    },
  },
  "/api/v1/championships/{championshipId}/bracket/generate": {
    post: {
      tags: ["Brackets"],
      summary: "Gera grupos e partidas da fase de grupos",
      operationId: "generateChampionshipBracket",
      "x-implementation-status": implemented,
      security: bearer,
      parameters: [championshipId],
      requestBody: {
        required: true,
        content: json({ $ref: "#/components/schemas/BracketGenerationRequest" }),
      },
      responses: {
        "201": success({
          type: "object",
          required: ["data"],
          additionalProperties: false,
          properties: { data: { $ref: "#/components/schemas/BracketViewDto" } },
        }),
        "409": error("Já existe chave para a temporada."),
        "422": error("Configuração inválida."),
      },
    },
  },
} as const;

const scoreboardProperties = {
  homeScore: nonNegativeInteger,
  awayScore: nonNegativeInteger,
  currentSetHomeScore: { type: ["integer", "null"], minimum: 0 },
  currentSetAwayScore: { type: ["integer", "null"], minimum: 0 },
  homePenaltyScore: { type: ["integer", "null"], minimum: 0 },
  awayPenaltyScore: { type: ["integer", "null"], minimum: 0 },
  homeYellowCards: nonNegativeInteger,
  homeRedCards: nonNegativeInteger,
  homeBlueCards: nonNegativeInteger,
  homeTwoMinutePenalties: nonNegativeInteger,
  awayYellowCards: nonNegativeInteger,
  awayRedCards: nonNegativeInteger,
  awayBlueCards: nonNegativeInteger,
  awayTwoMinutePenalties: nonNegativeInteger,
} as const;

const individualPlacementProperties = {
  firstPlaces: nonNegativeInteger,
  secondPlaces: nonNegativeInteger,
  thirdPlaces: nonNegativeInteger,
  fourthPlaces: nonNegativeInteger,
  fifthPlaces: nonNegativeInteger,
  sixthPlaces: nonNegativeInteger,
  seventhPlaces: nonNegativeInteger,
  eighthPlaces: nonNegativeInteger,
  ninthPlaces: nonNegativeInteger,
  tenthPlaces: nonNegativeInteger,
  eleventhPlaces: nonNegativeInteger,
  twelfthPlaces: nonNegativeInteger,
  thirteenthPlaces: nonNegativeInteger,
  fourteenthPlaces: nonNegativeInteger,
  fifteenthPlaces: nonNegativeInteger,
  sixteenthPlaces: nonNegativeInteger,
  seventeenthPlaces: nonNegativeInteger,
  eighteenthPlaces: nonNegativeInteger,
  nineteenthPlaces: nonNegativeInteger,
  twentiethPlaces: nonNegativeInteger,
} as const;

export const sportsCoreSchemas = {
  TeamSummary: {
    type: "object",
    required: ["id", "name", "city", "division"],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      name: { type: "string" },
      city: nullableString,
      division: { $ref: "#/components/schemas/TeamDivision" },
    },
  },
  SportSummary: {
    type: "object",
    required: ["id", "name", "code"],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      name: { type: "string" },
      code: nullableString,
    },
  },
  ChampionshipSummaryDto: {
    type: "object",
    required: ["id", "code", "name", "status", "currentSeasonYear", "usesDivisions", "defaultLocation"],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      code: { type: "string", enum: ["CLV", "SOCIETY", "INTERLAJE"] },
      name: { type: "string" },
      status: { $ref: "#/components/schemas/ChampionshipStatus" },
      currentSeasonYear: { type: "integer" },
      usesDivisions: { type: "boolean" },
      defaultLocation: nullableString,
    },
  },
  ChampionshipDto: {
    type: "object",
    required: [
      "id",
      "code",
      "name",
      "status",
      "currentSeasonYear",
      "usesDivisions",
      "defaultLocation",
      "createdAt",
    ],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      code: { type: "string", enum: ["CLV", "SOCIETY", "INTERLAJE"] },
      name: { type: "string" },
      status: { $ref: "#/components/schemas/ChampionshipStatus" },
      currentSeasonYear: { type: "integer" },
      usesDivisions: { type: "boolean" },
      defaultLocation: nullableString,
      createdAt: { type: "string", format: "date-time" },
    },
  },
  ChampionshipWriteRequest: {
    type: "object",
    properties: {
      code: { type: "string", enum: ["CLV", "SOCIETY", "INTERLAJE"] },
      name: { type: "string" },
      status: { $ref: "#/components/schemas/ChampionshipStatus" },
      currentSeasonYear: { type: "integer" },
      usesDivisions: { type: "boolean" },
      defaultLocation: nullableString,
    },
  },
  MatchSetDto: {
    type: "object",
    required: ["id", "setNumber", "homePoints", "awayPoints"],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      setNumber: { type: "integer", minimum: 1 },
      homePoints: nonNegativeInteger,
      awayPoints: nonNegativeInteger,
    },
  },
  MatchSetInput: {
    type: "object",
    required: ["setNumber", "homePoints", "awayPoints"],
    additionalProperties: false,
    properties: {
      setNumber: { type: "integer", minimum: 1, maximum: 20 },
      homePoints: nonNegativeInteger,
      awayPoints: nonNegativeInteger,
    },
  },
  MatchDto: {
    type: "object",
    required: [
      "id",
      "championshipId",
      "seasonYear",
      "division",
      "naipe",
      "supportsCards",
      "resultRule",
      "sportId",
      "homeTeamId",
      "awayTeamId",
      "location",
      "courtName",
      "scheduledDate",
      "queuePosition",
      "scheduledSlot",
      "scheduledStartTime",
      "startTime",
      "endTime",
      "status",
      "homeScore",
      "awayScore",
      "currentSetHomeScore",
      "currentSetAwayScore",
      "homePenaltyScore",
      "awayPenaltyScore",
      "homeYellowCards",
      "homeRedCards",
      "homeBlueCards",
      "homeTwoMinutePenalties",
      "awayYellowCards",
      "awayRedCards",
      "awayBlueCards",
      "awayTwoMinutePenalties",
      "isWalkover",
      "walkoverLoserTeamId",
      "isDoubleWalkover",
      "disqualificationId",
      "resolvedTieBreakerRule",
      "resolvedTieBreakWinnerTeamId",
      "isManualScheduleOverride",
      "manualRepresentationMode",
      "isPendingManualRelocation",
      "isScoreSheetReviewed",
      "createdAt",
      "groupNumber",
      "championship",
      "sport",
      "homeTeam",
      "awayTeam",
      "matchSets",
    ],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      championshipId: { type: "string", format: "uuid" },
      seasonYear: { type: "integer" },
      division: { $ref: "#/components/schemas/TeamDivision" },
      naipe: { $ref: "#/components/schemas/MatchNaipe" },
      supportsCards: { type: "boolean" },
      resultRule: { type: ["string", "null"], enum: ["POINTS", "SETS", null] },
      sportId: { type: "string", format: "uuid" },
      homeTeamId: { type: "string", format: "uuid" },
      awayTeamId: { type: "string", format: "uuid" },
      location: nullableString,
      courtName: nullableString,
      scheduledDate: { type: ["string", "null"], format: "date" },
      queuePosition: { type: ["integer", "null"] },
      scheduledSlot: { type: ["integer", "null"] },
      scheduledStartTime: nullableString,
      startTime: nullableString,
      endTime: nullableString,
      status: { $ref: "#/components/schemas/MatchStatus" },
      homeScore: nonNegativeInteger,
      awayScore: nonNegativeInteger,
      currentSetHomeScore: { type: ["integer", "null"], minimum: 0 },
      currentSetAwayScore: { type: ["integer", "null"], minimum: 0 },
      homePenaltyScore: { type: ["integer", "null"], minimum: 0 },
      awayPenaltyScore: { type: ["integer", "null"], minimum: 0 },
      homeYellowCards: nonNegativeInteger,
      homeRedCards: nonNegativeInteger,
      homeBlueCards: nonNegativeInteger,
      homeTwoMinutePenalties: nonNegativeInteger,
      awayYellowCards: nonNegativeInteger,
      awayRedCards: nonNegativeInteger,
      awayBlueCards: nonNegativeInteger,
      awayTwoMinutePenalties: nonNegativeInteger,
      isWalkover: { type: "boolean" },
      walkoverLoserTeamId: nullableUuid,
      isDoubleWalkover: { type: "boolean" },
      disqualificationId: nullableUuid,
      resolvedTieBreakerRule: nullableString,
      resolvedTieBreakWinnerTeamId: nullableUuid,
      isManualScheduleOverride: { type: "boolean" },
      manualRepresentationMode: nullableString,
      isPendingManualRelocation: { type: "boolean" },
      isScoreSheetReviewed: { type: "boolean" },
      createdAt: { type: "string", format: "date-time" },
      groupNumber: { type: ["integer", "null"] },
      championship: { $ref: "#/components/schemas/ChampionshipSummaryDto" },
      sport: { $ref: "#/components/schemas/SportSummary" },
      homeTeam: { $ref: "#/components/schemas/TeamSummary" },
      awayTeam: { $ref: "#/components/schemas/TeamSummary" },
      matchSets: { type: "array", items: { $ref: "#/components/schemas/MatchSetDto" } },
    },
  },
  ScoreboardUpdateRequest: {
    type: "object",
    minProperties: 1,
    additionalProperties: false,
    properties: {
      ...scoreboardProperties,
      sets: { type: "array", items: { $ref: "#/components/schemas/MatchSetInput" } },
    },
  },
  MatchFinishRequest: {
    type: "object",
    additionalProperties: false,
    properties: {
      ...scoreboardProperties,
      sets: { type: "array", items: { $ref: "#/components/schemas/MatchSetInput" } },
      isWalkover: { type: "boolean" },
      isDoubleWalkover: { type: "boolean" },
      walkoverLoserTeamId: nullableUuid,
    },
  },
  SeasonSettingsDto: {
    type: "object",
    required: [
      "id",
      "championshipId",
      "seasonYear",
      "divisionFormat",
      "divisionSettlementMode",
      "principalSlotsCount",
      "principalRelegationCount",
      "accessPromotionCount",
      "yellowCardResetPhase",
      "createdAt",
      "updatedAt",
    ],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      championshipId: { type: "string", format: "uuid" },
      seasonYear: { type: "integer" },
      divisionFormat: { type: "string", enum: ["SEPARATED", "UNIFIED"] },
      divisionSettlementMode: {
        type: "string",
        enum: ["NONE", "PROMOTION_RELEGATION", "TOP_N_TO_PRINCIPAL"],
      },
      principalSlotsCount: { type: ["integer", "null"] },
      principalRelegationCount: { type: ["integer", "null"] },
      accessPromotionCount: { type: ["integer", "null"] },
      yellowCardResetPhase: { type: "string" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
    },
  },
  SeasonSettingsWriteRequest: {
    type: "object",
    properties: {
      divisionFormat: { type: "string", enum: ["SEPARATED", "UNIFIED"] },
      divisionSettlementMode: {
        type: "string",
        enum: ["NONE", "PROMOTION_RELEGATION", "TOP_N_TO_PRINCIPAL"],
      },
      principalSlotsCount: { type: ["integer", "null"] },
      principalRelegationCount: { type: ["integer", "null"] },
      accessPromotionCount: { type: ["integer", "null"] },
      yellowCardResetPhase: { type: "string" },
    },
  },
  CollectiveStandingDto: {
    type: "object",
    required: [
      "id",
      "championshipId",
      "seasonYear",
      "sportId",
      "sportName",
      "sportCode",
      "naipe",
      "division",
      "teamId",
      "teamName",
      "teamCity",
      "played",
      "wins",
      "draws",
      "losses",
      "goalsFor",
      "goalsAgainst",
      "goalDiff",
      "points",
      "yellowCards",
      "redCards",
      "blueCards",
      "twoMinutePenalties",
      "setsFor",
      "setsAgainst",
      "rallyPointsFor",
      "rallyPointsAgainst",
      "source",
      "position",
      "tieBreakCascade",
    ],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      championshipId: { type: "string", format: "uuid" },
      seasonYear: { type: "integer" },
      sportId: { type: "string", format: "uuid" },
      sportName: { type: "string" },
      sportCode: nullableString,
      naipe: { $ref: "#/components/schemas/MatchNaipe" },
      division: { $ref: "#/components/schemas/TeamDivision" },
      teamId: { type: "string", format: "uuid" },
      teamName: { type: "string" },
      teamCity: { type: "string" },
      played: nonNegativeInteger,
      wins: nonNegativeInteger,
      draws: nonNegativeInteger,
      losses: nonNegativeInteger,
      goalsFor: { type: "integer" },
      goalsAgainst: { type: "integer" },
      goalDiff: { type: "integer" },
      points: { type: "number" },
      yellowCards: nonNegativeInteger,
      redCards: nonNegativeInteger,
      blueCards: nonNegativeInteger,
      twoMinutePenalties: nonNegativeInteger,
      setsFor: nonNegativeInteger,
      setsAgainst: nonNegativeInteger,
      rallyPointsFor: nonNegativeInteger,
      rallyPointsAgainst: nonNegativeInteger,
      source: { type: "string", const: "COLLECTIVE" },
      position: { type: "integer", minimum: 1 },
      tieBreakCascade: { type: "array", items: { type: "string" } },
    },
  },
  IndividualStandingDto: {
    type: "object",
    required: [
      "id",
      "championshipId",
      "seasonYear",
      "sportId",
      "sportName",
      "sportCode",
      "naipe",
      "division",
      "teamId",
      "teamName",
      "teamCity",
      "totalPoints",
      "scoredEventsCount",
      "firstPlaces",
      "secondPlaces",
      "thirdPlaces",
      "fourthPlaces",
      "fifthPlaces",
      "sixthPlaces",
      "seventhPlaces",
      "eighthPlaces",
      "ninthPlaces",
      "tenthPlaces",
      "eleventhPlaces",
      "twelfthPlaces",
      "thirteenthPlaces",
      "fourteenthPlaces",
      "fifteenthPlaces",
      "sixteenthPlaces",
      "seventeenthPlaces",
      "eighteenthPlaces",
      "nineteenthPlaces",
      "twentiethPlaces",
      "relayPointsTotal",
      "source",
      "position",
    ],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      championshipId: { type: "string", format: "uuid" },
      seasonYear: { type: "integer" },
      sportId: { type: "string", format: "uuid" },
      sportName: { type: "string" },
      sportCode: nullableString,
      naipe: { $ref: "#/components/schemas/MatchNaipe" },
      division: { $ref: "#/components/schemas/TeamDivision" },
      teamId: { type: "string", format: "uuid" },
      teamName: { type: "string" },
      teamCity: { type: "string" },
      totalPoints: { type: "number" },
      scoredEventsCount: nonNegativeInteger,
      ...individualPlacementProperties,
      relayPointsTotal: { type: "number" },
      source: { type: "string", const: "INDIVIDUAL" },
      position: { type: "integer", minimum: 1 },
    },
  },
  StandingDto: {
    oneOf: [
      { $ref: "#/components/schemas/CollectiveStandingDto" },
      { $ref: "#/components/schemas/IndividualStandingDto" },
    ],
    discriminator: { propertyName: "source" },
  },
  CalendarMatchDto: {
    type: "object",
    required: [
      "id",
      "championshipId",
      "seasonYear",
      "sportId",
      "sportName",
      "naipe",
      "division",
      "status",
      "scheduledDate",
      "queuePosition",
      "scheduledSlot",
      "scheduledStartTime",
      "startTime",
      "endTime",
      "location",
      "courtName",
      "homeTeamId",
      "homeTeamName",
      "awayTeamId",
      "awayTeamName",
      "homeScore",
      "awayScore",
    ],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      championshipId: { type: "string", format: "uuid" },
      seasonYear: { type: "integer" },
      sportId: { type: "string", format: "uuid" },
      sportName: { type: "string" },
      naipe: { $ref: "#/components/schemas/MatchNaipe" },
      division: { $ref: "#/components/schemas/TeamDivision" },
      status: { $ref: "#/components/schemas/MatchStatus" },
      scheduledDate: { type: ["string", "null"], format: "date" },
      queuePosition: { type: ["integer", "null"] },
      scheduledSlot: { type: ["integer", "null"] },
      scheduledStartTime: nullableString,
      startTime: nullableString,
      endTime: nullableString,
      location: nullableString,
      courtName: nullableString,
      homeTeamId: { type: "string", format: "uuid" },
      homeTeamName: { type: "string" },
      awayTeamId: { type: "string", format: "uuid" },
      awayTeamName: { type: "string" },
      homeScore: nonNegativeInteger,
      awayScore: nonNegativeInteger,
    },
  },
  BracketGenerationRequest: {
    type: "object",
    required: ["seasonYear", "competitions"],
    properties: {
      seasonYear: { type: "integer" },
      payloadSnapshot: { type: "object", additionalProperties: true },
      competitions: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          required: ["sportId", "naipe", "groupsCount", "qualifiersPerGroup", "groups"],
          properties: {
            sportId: { type: "string", format: "uuid" },
            naipe: { $ref: "#/components/schemas/MatchNaipe" },
            division: { anyOf: [{ $ref: "#/components/schemas/TeamDivision" }, { type: "null" }] },
            groupsCount: { type: "integer", minimum: 1 },
            qualifiersPerGroup: { type: "integer", minimum: 1 },
            thirdPlaceMode: {
              type: "string",
              enum: ["NONE", "MATCH", "CHAMPION_SEMIFINAL_LOSER"],
            },
            shouldCompleteKnockoutWithBestSecondPlacedTeams: { type: "boolean" },
            knockoutPairingMode: {
              type: "string",
              enum: ["LINEAR", "RANKING_ALTERNATING", "CLASSIC_SEEDED"],
            },
            groups: {
              type: "array",
              items: {
                type: "object",
                required: ["groupNumber", "teamIds"],
                properties: {
                  groupNumber: { type: "integer", minimum: 1 },
                  teamIds: {
                    type: "array",
                    minItems: 2,
                    items: { type: "string", format: "uuid" },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
  BracketViewDto: {
    type: "object",
    required: ["edition", "competitions"],
    properties: {
      edition: { type: ["object", "null"], additionalProperties: true },
      competitions: { type: "array", items: { type: "object", additionalProperties: true } },
    },
  },
} as const;
