const implemented = "implemented" as const;
const json = (schema: unknown) => ({ "application/json": { schema } });
const success = (schema: unknown) => ({
  description: "Operação concluída.",
  content: json(schema),
});

const championshipId = {
  name: "championshipId",
  in: "path",
  required: true,
  schema: { type: "string", format: "uuid" },
};

const seasonYearQuery = {
  name: "seasonYear",
  in: "query",
  required: true,
  schema: { type: "integer", minimum: 2000, maximum: 2100 },
};

const nullableString = { type: ["string", "null"] } as const;
const nullableUuid = { type: ["string", "null"], format: "uuid" } as const;
const nonNegativeInteger = { type: "integer", minimum: 0 } as const;

export const sportsCoreContractPaths = {
  "/api/v1/matches": {
    get: {
      tags: ["Matches"],
      summary: "Lista jogos do núcleo esportivo",
      operationId: "listMatches",
      "x-implementation-status": implemented,
      parameters: [
        { name: "championshipId", in: "query", schema: { type: "string", format: "uuid" } },
        {
          name: "seasonYear",
          in: "query",
          schema: { type: "integer", minimum: 2000, maximum: 2100 },
        },
        {
          name: "status",
          in: "query",
          style: "form",
          explode: true,
          schema: { type: "array", items: { $ref: "#/components/schemas/MatchStatus" } },
        },
        { name: "sportId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "teamId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "naipe", in: "query", schema: { $ref: "#/components/schemas/MatchNaipe" } },
        { name: "division", in: "query", schema: { $ref: "#/components/schemas/TeamDivision" } },
        { name: "groupNumber", in: "query", schema: { type: "integer", minimum: 1 } },
        { name: "location", in: "query", schema: { type: "string" } },
        { name: "courtName", in: "query", schema: { type: "string" } },
        { name: "from", in: "query", schema: { type: "string", format: "date" } },
        { name: "to", in: "query", schema: { type: "string", format: "date" } },
        {
          name: "matchId",
          in: "query",
          style: "form",
          explode: true,
          schema: { type: "array", items: { type: "string", format: "uuid" } },
        },
        { $ref: "#/components/parameters/Page" },
        { $ref: "#/components/parameters/PageSize" },
        {
          name: "sort",
          in: "query",
          schema: {
            type: "string",
            enum: ["scheduledDate", "queuePosition", "createdAt"],
            default: "scheduledDate",
          },
        },
        { $ref: "#/components/parameters/Order" },
      ],
      responses: {
        "200": success({
          type: "object",
          required: ["data", "meta"],
          additionalProperties: false,
          properties: {
            data: { type: "array", items: { $ref: "#/components/schemas/MatchDto" } },
            meta: { $ref: "#/components/schemas/PaginationMeta" },
          },
        }),
      },
    },
  },
  "/api/v1/championships/{championshipId}/standings": {
    get: {
      tags: ["Standings"],
      summary: "Obtém classificação oficial ordenada pelo backend",
      operationId: "getChampionshipStandings",
      "x-implementation-status": implemented,
      parameters: [
        championshipId,
        seasonYearQuery,
        { name: "sportId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "naipe", in: "query", schema: { $ref: "#/components/schemas/MatchNaipe" } },
        { name: "division", in: "query", schema: { $ref: "#/components/schemas/TeamDivision" } },
        { $ref: "#/components/parameters/Page" },
        { $ref: "#/components/parameters/PageSize" },
      ],
      responses: {
        "200": success({
          type: "object",
          required: ["data", "meta"],
          additionalProperties: false,
          properties: {
            data: { type: "array", items: { $ref: "#/components/schemas/StandingDto" } },
            meta: { $ref: "#/components/schemas/PaginationMeta" },
          },
        }),
      },
    },
  },
  "/api/v1/championships/{championshipId}/calendar": {
    get: {
      tags: ["Championships"],
      summary: "Obtém calendário público do campeonato",
      operationId: "getChampionshipCalendar",
      "x-implementation-status": implemented,
      parameters: [
        championshipId,
        seasonYearQuery,
        { name: "from", in: "query", schema: { type: "string", format: "date" } },
        { name: "to", in: "query", schema: { type: "string", format: "date" } },
        { name: "sportId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "teamId", in: "query", schema: { type: "string", format: "uuid" } },
        { name: "naipe", in: "query", schema: { $ref: "#/components/schemas/MatchNaipe" } },
        { name: "division", in: "query", schema: { $ref: "#/components/schemas/TeamDivision" } },
        { $ref: "#/components/parameters/Page" },
        { $ref: "#/components/parameters/PageSize" },
      ],
      responses: {
        "200": success({
          type: "object",
          required: ["data", "meta"],
          additionalProperties: false,
          properties: {
            data: {
              type: "array",
              items: { $ref: "#/components/schemas/CalendarMatchDto" },
            },
            meta: { $ref: "#/components/schemas/PaginationMeta" },
          },
        }),
      },
    },
  },
} as const;

export const sportsCoreContractSchemas = {
  TeamSummary: {
    type: "object",
    required: ["id", "name", "city", "division"],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      name: { type: "string" },
      city: nullableString,
      division: {
        anyOf: [{ $ref: "#/components/schemas/TeamDivision" }, { type: "null" }],
      },
    },
  },
  SportSummaryDto: {
    type: "object",
    required: ["id", "name", "code"],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      name: { type: "string" },
      code: nullableString,
    },
  },
  ChampionshipSummaryDto: {
    type: "object",
    required: [
      "id",
      "code",
      "name",
      "status",
      "currentSeasonYear",
      "usesDivisions",
      "defaultLocation",
    ],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      code: { type: "string", enum: ["CLV", "SOCIETY", "INTERLAJE"] },
      name: { type: "string" },
      status: { $ref: "#/components/schemas/ChampionshipStatus" },
      currentSeasonYear: { type: "integer" },
      usesDivisions: { type: "boolean" },
      defaultLocation: nullableString,
    },
  },
  MatchSetDto: {
    type: "object",
    required: ["id", "setNumber", "homePoints", "awayPoints"],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      setNumber: { type: "integer", minimum: 1 },
      homePoints: nonNegativeInteger,
      awayPoints: nonNegativeInteger,
    },
  },
  MatchDto: {
    type: "object",
    required: [
      "id",
      "championshipId",
      "seasonYear",
      "division",
      "naipe",
      "supportsCards",
      "sportId",
      "homeTeamId",
      "awayTeamId",
      "location",
      "courtName",
      "scheduledDate",
      "queuePosition",
      "scheduledSlot",
      "scheduledStartTime",
      "startTime",
      "endTime",
      "status",
      "homeScore",
      "awayScore",
      "isPendingManualRelocation",
      "createdAt",
      "groupNumber",
      "championship",
      "sport",
      "homeTeam",
      "awayTeam",
      "matchSets",
    ],
    additionalProperties: true,
    properties: {
      id: { type: "string", format: "uuid" },
      championshipId: { type: "string", format: "uuid" },
      seasonYear: { type: "integer" },
      division: {
        anyOf: [{ $ref: "#/components/schemas/TeamDivision" }, { type: "null" }],
      },
      naipe: { $ref: "#/components/schemas/MatchNaipe" },
      supportsCards: { type: "boolean" },
      resultRule: nullableString,
      sportId: { type: "string", format: "uuid" },
      homeTeamId: { type: "string", format: "uuid" },
      awayTeamId: { type: "string", format: "uuid" },
      location: nullableString,
      courtName: nullableString,
      scheduledDate: { type: ["string", "null"], format: "date" },
      queuePosition: { type: ["integer", "null"] },
      scheduledSlot: { type: ["integer", "null"] },
      scheduledStartTime: nullableString,
      startTime: { type: ["string", "null"], format: "date-time" },
      endTime: { type: ["string", "null"], format: "date-time" },
      status: { $ref: "#/components/schemas/MatchStatus" },
      homeScore: nonNegativeInteger,
      awayScore: nonNegativeInteger,
      isPendingManualRelocation: { type: "boolean" },
      createdAt: { type: "string", format: "date-time" },
      groupNumber: { type: ["integer", "null"] },
      championship: { $ref: "#/components/schemas/ChampionshipSummaryDto" },
      sport: { $ref: "#/components/schemas/SportSummaryDto" },
      homeTeam: { $ref: "#/components/schemas/TeamSummary" },
      awayTeam: { $ref: "#/components/schemas/TeamSummary" },
      matchSets: {
        type: "array",
        items: { $ref: "#/components/schemas/MatchSetDto" },
      },
      walkoverLoserTeamId: nullableUuid,
      disqualificationId: nullableUuid,
      resolvedTieBreakWinnerTeamId: nullableUuid,
    },
  },
  StandingDto: {
    type: "object",
    required: [
      "id",
      "championshipId",
      "seasonYear",
      "sportId",
      "sportName",
      "sportCode",
      "naipe",
      "division",
      "teamId",
      "teamName",
      "teamCity",
      "source",
      "position",
    ],
    additionalProperties: true,
    properties: {
      id: { type: "string", format: "uuid" },
      championshipId: { type: "string", format: "uuid" },
      seasonYear: { type: "integer" },
      sportId: { type: "string", format: "uuid" },
      sportName: { type: "string" },
      sportCode: nullableString,
      naipe: { $ref: "#/components/schemas/MatchNaipe" },
      division: {
        anyOf: [{ $ref: "#/components/schemas/TeamDivision" }, { type: "null" }],
      },
      teamId: { type: "string", format: "uuid" },
      teamName: { type: "string" },
      teamCity: { type: "string" },
      source: { type: "string", enum: ["COLLECTIVE", "INDIVIDUAL"] },
      position: { type: "integer", minimum: 1 },
      played: nonNegativeInteger,
      wins: nonNegativeInteger,
      draws: nonNegativeInteger,
      losses: nonNegativeInteger,
      goalsFor: nonNegativeInteger,
      goalsAgainst: nonNegativeInteger,
      goalDiff: { type: "integer" },
      points: { type: "number" },
      yellowCards: nonNegativeInteger,
      redCards: nonNegativeInteger,
      blueCards: nonNegativeInteger,
      twoMinutePenalties: nonNegativeInteger,
      setsFor: nonNegativeInteger,
      setsAgainst: nonNegativeInteger,
      rallyPointsFor: nonNegativeInteger,
      rallyPointsAgainst: nonNegativeInteger,
      totalPoints: { type: "number" },
      scoredEventsCount: nonNegativeInteger,
      firstPlaces: nonNegativeInteger,
      secondPlaces: nonNegativeInteger,
      thirdPlaces: nonNegativeInteger,
      fourthPlaces: nonNegativeInteger,
      fifthPlaces: nonNegativeInteger,
      sixthPlaces: nonNegativeInteger,
      seventhPlaces: nonNegativeInteger,
      eighthPlaces: nonNegativeInteger,
      ninthPlaces: nonNegativeInteger,
      tenthPlaces: nonNegativeInteger,
      eleventhPlaces: nonNegativeInteger,
      twelfthPlaces: nonNegativeInteger,
      thirteenthPlaces: nonNegativeInteger,
      fourteenthPlaces: nonNegativeInteger,
      fifteenthPlaces: nonNegativeInteger,
      sixteenthPlaces: nonNegativeInteger,
      seventeenthPlaces: nonNegativeInteger,
      eighteenthPlaces: nonNegativeInteger,
      nineteenthPlaces: nonNegativeInteger,
      twentiethPlaces: nonNegativeInteger,
      relayPointsTotal: { type: "number" },
      tieBreakCascade: { type: "array", items: { type: "string" } },
    },
  },
  CalendarMatchDto: {
    type: "object",
    required: [
      "id",
      "championshipId",
      "seasonYear",
      "sportId",
      "sportName",
      "naipe",
      "division",
      "status",
      "scheduledDate",
      "queuePosition",
      "scheduledSlot",
      "scheduledStartTime",
      "startTime",
      "endTime",
      "location",
      "courtName",
      "homeTeamId",
      "homeTeamName",
      "awayTeamId",
      "awayTeamName",
      "homeScore",
      "awayScore",
    ],
    additionalProperties: false,
    properties: {
      id: { type: "string", format: "uuid" },
      championshipId: { type: "string", format: "uuid" },
      seasonYear: { type: "integer" },
      sportId: { type: "string", format: "uuid" },
      sportName: { type: "string" },
      naipe: { $ref: "#/components/schemas/MatchNaipe" },
      division: {
        anyOf: [{ $ref: "#/components/schemas/TeamDivision" }, { type: "null" }],
      },
      status: { $ref: "#/components/schemas/MatchStatus" },
      scheduledDate: { type: ["string", "null"], format: "date" },
      queuePosition: { type: ["integer", "null"] },
      scheduledSlot: { type: ["integer", "null"] },
      scheduledStartTime: nullableString,
      startTime: { type: ["string", "null"], format: "date-time" },
      endTime: { type: ["string", "null"], format: "date-time" },
      location: nullableString,
      courtName: nullableString,
      homeTeamId: { type: "string", format: "uuid" },
      homeTeamName: { type: "string" },
      awayTeamId: { type: "string", format: "uuid" },
      awayTeamName: { type: "string" },
      homeScore: nonNegativeInteger,
      awayScore: nonNegativeInteger,
    },
  },
} as const;
